language: go

go:
  - "1.10.x"

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install: 
  - go get -u github.com/mitchellh/gox # cross compile
  - dep ensure

script:
  - go build
  - gox -os "linux darwin windows" -arch "amd64" -osarch="windows/386" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags "-X main.buildStamp=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.gitRevision=`git describe --tags || git rev-parse HEAD` -s -w"

deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true

