source 'https://rubygems.org'

gem 'test-kitchen'
gem 'pry'
gem 'rake'
gem 'kitchen-transport-rsync-ssh', :git => 'https://github.com/guskovd/kitchen-transport-rsync-ssh.git'
gem 'kitchen-docker', :git => 'https://github.com/guskovd/kitchen-docker.git', :branch => 'use_internal_docker_network'
gem 'travis'
gem 'kitchen-provisioner-local_shell'
gem 'kitchen-docker_cli'
gem 'kitchen-transport-rsync'
